services:
  server: 
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    networks:
      - frontend
    volumes:
      - ./app:/usr/share/nginx/omekas
      - ./src/themes:/usr/share/nginx/omekas/themes
      - ./src/modules:/usr/share/nginx/omekas/modules
      - ./src/files:/usr/share/nginx/omekas/files
    configs:
      - source: nginx.app.conf
        target: /etc/nginx/conf.d/omekas.conf
      - source: omekas-db.ini
        target: /usr/share/nginx/omekas/config/database.ini

  app:
    build: 
      dockerfile: ./utils/app.Dockerfile
    restart: always
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
    volumes:
      - ./app:/usr/share/nginx/omekas
      - ./src/themes:/usr/share/nginx/omekas/themes
      - ./src/modules:/usr/share/nginx/omekas/modules
      - ./src/files:/usr/share/nginx/omekas/files
    configs:
      - source: php-fpm.conf
        target: /usr/local/etc/php-fpm.d/omekas.conf
      - source: omekas-db.ini
        target: /usr/share/nginx/omekas/config/database.ini

  db:
    image: mariadb:latest
    restart: always
    ports: 
      - 3306:3306
    networks:
      - backend
    volumes:
      - ./db:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

networks:
  frontend: {}
  backend: {}

configs:
  nginx.app.conf:
    file: ./config/nginx.app.conf
  php-fpm.conf:
    file: ./config/php-fpm.conf
  omekas-db.ini:
    file: ./config/omekas-db.ini
  omekas.config.php:
    file: ./config/omekas.config.php

  