services:
  web: 
    build:
      dockerfile: ./utils/web.Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - frontend
    volumes: 
      - files:/usr/share/nginx/omekas/files
      - sideload:/usr/share/nginx/omekas/sideload
      - logs:/usr/share/nginx/omekas/logs
    configs:
      - source: omekas-db.ini
        target: /usr/share/nginx/omekas/config/database.ini
      - source: omekas.config.php
        target: /usr/share/nginx/omekas/config/local.config.php
      - source: module.config.php
        target: /usr/share/nginx/omekas/application/config/module.config.php
      - source: fastcgi_params
        target: /etc/nginx/fastcgi_params
      - source: nginx.app.conf
        target: /etc/nginx/conf.d/omekas.conf
      - source: nginx.conf
        target: /etc/nginx/nginx.conf

  app:
    build: 
      dockerfile: ./utils/app.Dockerfile
    restart: always
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
    volumes:
      - files:/usr/share/nginx/omekas/files
      - sideload:/usr/share/nginx/omekas/sideload
      - logs:/usr/share/nginx/omekas/logs
    configs:
      - source: omekas-db.ini
        target: /usr/share/nginx/omekas/config/database.ini
      - source: omekas.config.php
        target: /usr/share/nginx/omekas/config/local.config.php
      - source: module.config.php
        target: /usr/share/nginx/omekas/application/config/module.config.php
      - source: php-fpm.conf
        target: /usr/local/etc/php-fpm.d/omekas.conf

  db:
    image: mariadb:latest
    restart: always
    ports: 
      - 3306:3306
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
  
  # One time file or data ingestion service.
  # ingest:
  #   build:
  #     dockerfile: ./utils/ingest.Dockerfile
  #   volumes:
  #     - sideload:/usr/share/nginx/omekas/sideload

networks:
  frontend: {}
  backend: {}

volumes:
  files: {}
  sideload: {}
  logs: {}
  db: {}

configs:
  nginx.app.conf:
    file: ./config/nginx.app.conf
  nginx.conf:
    file: ./config/nginx.conf
  fastcgi_params:
    file: ./config/fastcgi_params
  php-fpm.conf:
    file: ./config/php-fpm.conf
  omekas-db.ini:
    file: ./config/omekas-db.ini
  omekas.config.php:
    file: ./config/omekas.config.php
  module.config.php:
    file: ./config/module.config.php
