#!/usr/bin/env bash


__construct() {
    return true
}

# @name cli.info Prints the available CLI commands and their documentation.
# @returns 0.
cli.info() {
    for key val in ${(kv)DEPS}; do
        case $key in
            (docs | env) continue ;;
            (commands | git) 
                __info $val 
                continue
                ;;
            (*) continue ;;
        esac
    done
    
    return 0
}

__construct