#!/usr/bin/env bash


__construct() {
    return true
}

# @name info Prints a specific dependency's commands and docs, or all of the commands available if no key is given.
# @arg { string } $1 key Optional. The name of the depenedency to print the documentation for.
# @returns 0.
info() {
    if [ ! -z "${1[@]}" ]; then
        __info $DEPS[$1]
        return 0
    else
        for key val in ${(kv)DEPS}; do
            case $key in
                (docs) continue ;;
                (env | commands | git) 
                    __info $val 
                    continue
                    ;;
                (*) continue ;;
            esac
        done
    fi
    
    return 0
}

# @name deps Prints the list of dependencies.
# @returns 0.
deps() {
    for key in ${(k)DEPS}; do
        printf "$COLOR[orange]%s$COLOR[reset] \n" $key
    done

    return 0
}

__construct