#!/usr/bin/env bash

__construct() {
    declare -grA DEPS=(
        [env]=$1/environment
        [commands]=$1/commands
        [git]=$1/git
        [docker]=$1/docker
        [docs]=$1/docs
    )

    for key val in ${(kv)DEPS}; do
        if source $val; then
            printf "✅ Sourced $COLOR[orange]%s$COLOR[reset] from $COLOR[orange]%s$COLOR[reset] \n" $key $val
        fi
    done

    printf "\n✅ Sources loaded. Run $COLOR[yellow]'info'$COLOR[reset] for help. \n"

    return 0
}

__construct $1
